project:
  type: book

book:
  chapters:
    - index.qmd
    - summary.qmd
    - chapters/chapter1.qmd
    - chapters/chapter2.qmd
    - chapters/chapter3.qmd
    - chapters/chapter4.qmd
    - chapters/conclusioni.qmd
    - chapters/references.qmd

bibliography: files/references.bib
csl: apa.csl
lang: it

format:
  pdf:
    documentclass: report
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: false
    toc-title: "Indice"
    linestretch: 1.5

crossref:
  fig-title: Figura # figure name in the caption
  fig-prefix: Figura # figure name in the text
  tbl-title: Tabella # table name in the caption
  tbl-prefix: Tabella # table name in the text
  lst-title: Codice # code name in the caption
  lst-prefix: Codice # code name in the text
  eq-title: Equazione # equation name in the caption
  eq-prefix: Equazione # equation name in the text
  
filters:
  - first-line-indent

department: Dipartimento di Psicologia dello Sviluppo e della Socializzazione
degree: Corso di laurea magistrale in Psicologia Clinica dello Sviluppo
thesis: Tesi di laurea magistrale
title-ita: "Multiverse Meta-Analysis: proposta di un nuovo approccio inferenziale 
con una applicazione alla psicoterapia della depressione"
title-eng: "Multiverse Meta-Analysis: Proposal of a New Inferential Approach with 
an Application to Depression Psychotherapy"
supervisor-prefix: Relatore
supervisor-name: Prof. Gianmarco Altoè
cosupervisor-prefix: Correlatore
cosupervisor-name: Dott. Filippo Gambarota
student-prefix: Laureando
student-name: Matteo Manente
matricola-prefix: Matricola
matricola: 2115067
academic-year-prefix: Anno Accademico
academic-year: 2024/2025